/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menuAdmin;

import java.awt.Color;

/**
 *
 * @author waldi
 */
public class JFKardex extends javax.swing.JFrame {

    /**
     * Creates new form JFKardex
     */
    public JFKardex (String nombreUsuario, boolean conectado) {
        setTitle("Kardex");
        initComponents();
        setUsuario(nombreUsuario);
        setEstadoConexion(conectado);
    }
    
    public void setUsuario(String usuario) {
        lblUsuario.setText(usuario);
    }

    public void setEstadoConexion(boolean conectado) {
        if (conectado) {
            lblEstado.setText("Conectado");
            lblEstado.setForeground(Color.GREEN);
        } else {
            lblEstado.setText("Desconectado");
            lblEstado.setForeground(Color.RED);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        lblEstadoTitulo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblUsuarioTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMenu.setText("Menú");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblEstadoTitulo.setText("Estado:");

        lblEstado.setText("none");

        lblUsuarioTitulo.setText("Usuario:");

        lblUsuario.setText("none");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarioTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstadoTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstado)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnMenu)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(btnMenu)
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoTitulo)
                    .addComponent(lblEstado)
                    .addComponent(lblUsuarioTitulo)
                    .addComponent(lblUsuario))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        menuAdmin.Opciones opciones = new menuAdmin.Opciones(lblUsuario.getText().replace("Usuario: ", ""), true);
        opciones.setVisible(true);

        // Cerrar el JFrame Opciones actual
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioTitulo;
    // End of variables declaration//GEN-END:variables
}
