/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menuAdmin;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author waldi
 */
public class JFKardex extends javax.swing.JFrame {

    /**
     * Creates new form JFKardex
     */
    public JFKardex (String nombreUsuario, boolean conectado, String rol) {
        setTitle("Kardex");
        initComponents();
        cargarMovimientos();
        setUsuario(nombreUsuario, rol);
        setEstadoConexion(conectado);
    }
    
    public void setUsuario(String usuario, String rol) {
        lblUsuario.setText(usuario);
        lblRol.setText(rol);
    }

    public void setEstadoConexion(boolean conectado) {
        if (conectado) {
            lblEstado.setText("Conectado");
            lblEstado.setForeground(Color.GREEN);
        } else {
            lblEstado.setText("Desconectado");
            lblEstado.setForeground(Color.RED);
        }
    }
    
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{"Código", "Tipo", "Código Lote", "Cantidad", "Costo", "Fecha"}, 0
    );

    private void cargarMovimientos() {
        // Crear el modelo de la tabla con columnas
        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"Código", "Tipo", "Código Lote", "Cantidad", "Costo", "Fecha"}, 0
        );

        // Intentar conectarse a la base de datos
        try (Connection conn = Conexion.Conexion.getConexion();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(
                 "SELECT mi.codigo, tm.nombre AS tipo, mi.codigo_lote, mi.cantidad, mi.costo, mi.fecha " +
                 "FROM movimiento_inventario mi " +
                 "JOIN tipo_movimiento tm ON mi.idtipo = tm.idtipo " +
                 "ORDER BY mi.fecha DESC"
             )) {

            // Recorrer los resultados y agregarlos al modelo
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("codigo"),
                    rs.getString("tipo"),
                    rs.getString("codigo_lote"),
                    rs.getInt("cantidad"),
                    rs.getDouble("costo"),
                    rs.getDate("fecha")
                });
            }

            // Asignar el modelo a la tabla
            tablaMovimientos.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar movimientos: " + e.getMessage());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        lblEstadoTitulo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblUsuarioTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblKardex = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMovimientos = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        lblRolTitulo = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMenu.setText("Menú");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblEstadoTitulo.setText("Estado:");

        lblEstado.setText("none");

        lblUsuarioTitulo.setText("Usuario:");

        lblUsuario.setText("none");

        lblKardex.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblKardex.setText("Movimientos de Inventario: Kardex");

        tablaMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaMovimientos);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lblRolTitulo.setText("Rol:");

        lblRol.setText("none");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUsuarioTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsuario)
                        .addGap(230, 230, 230)
                        .addComponent(lblRolTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstadoTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstado)))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(lblKardex)
                .addGap(203, 203, 203))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblKardex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoTitulo)
                    .addComponent(lblEstado)
                    .addComponent(lblUsuarioTitulo)
                    .addComponent(lblUsuario)
                    .addComponent(lblRolTitulo)
                    .addComponent(lblRol))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        menuAdmin.Opciones opciones = new menuAdmin.Opciones(lblUsuario.getText().replace("Usuario: ", ""), true, lblRol.getText().replace("Rol: ", ""));
        opciones.setVisible(true);

        // Cerrar el JFrame Opciones actual
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cargarMovimientos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoTitulo;
    private javax.swing.JLabel lblKardex;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblRolTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioTitulo;
    private javax.swing.JTable tablaMovimientos;
    // End of variables declaration//GEN-END:variables
}
