/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menuAdmin;

import dao.UsuarioDAO;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author waldi
 */
public class JFUsuarios extends javax.swing.JFrame {
    UsuarioDAO dao = new UsuarioDAO();
    /**
     * Creates new form JFUsuarios
     */
    public JFUsuarios(String nombreUsuario, boolean conectado, String rol) {
        setTitle("Usuarios");
        initComponents();
        setUsuario(nombreUsuario, rol);
        setEstadoConexion(conectado);
        cargarUsuarios();
    }
    
    public void setUsuario(String usuario, String rol) {
        lblUsuario.setText(usuario);
        lblRolUsuario.setText(rol);
    }

    public void setEstadoConexion(boolean conectado) {
        if (conectado) {
            lblEstado.setText("Conectado");
            lblEstado.setForeground(Color.GREEN);
        } else {
            lblEstado.setText("Desconectado");
            lblEstado.setForeground(Color.RED);
        }
    }
    
    private void cargarUsuarios() {
        // Crear el modelo de la tabla con columnas
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"ID", "Nombre", "Edad", "Rol", "Contraseña"}, 0);

        // Intentar conectarse a la base de datos
        try (Connection conn = Conexion.Conexion.getConexion();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM usuario ORDER BY id")) {

            // Recorrer los resultados y agregarlos al modelo
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("nombre"),
                    rs.getInt("edad"),       // Si edad es numérico
                    rs.getString("rol"),
                    rs.getString("contraseña")
                });
            }

            // Asignar el modelo a la tabla
            tablaUsuarios.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage());
        }
    }
    
    private void limpiarCampos() {
        String t = "";
        txtID.setText(t);
        txtNombre.setText(t);
        txtPassword.setText(t);
        txtEdad.setText(t);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        cbxRol = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        txtEdad = new javax.swing.JTextField();
        lblUsuarioTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblEstadoTitulo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblRolTitulo = new javax.swing.JLabel();
        lblRolUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblID.setText("ID:");

        lblUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblUsuarios.setText("Usuarios");

        txtID.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtIDComponentAdded(evt);
            }
        });
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblPassword.setText("Contraseña");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        lblEdad.setText("Edad");

        lblRol.setText("Rol");

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Gestor de Inventario", "Bodeguero", "Auditor" }));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnMenu.setText("Regresar a Menú");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        txtEdad.setText("0000");
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        lblUsuarioTitulo.setText("Usuario:");

        lblUsuario.setText("none");

        lblEstado.setText("none");

        lblEstadoTitulo.setText("Estado:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nota: Presiona Enter cada que llenes un espacio");

        lblRolTitulo.setText("Rol:");

        lblRolUsuario.setText("none");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(lblUsuarios))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(lblEdad)
                                .addGap(18, 18, 18)
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(lblRol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnAgregar)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnEditar)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnEliminar))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblUsuarioTitulo)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblUsuario)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnActualizar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnCancelar))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblRolTitulo)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblRolUsuario)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnMenu)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblEstadoTitulo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblEstado)))))
                            .addComponent(jLabel1))))
                .addGap(24, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblUsuarios)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad)
                    .addComponent(lblRol)
                    .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar)
                    .addComponent(btnMenu)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioTitulo)
                    .addComponent(lblUsuario)
                    .addComponent(lblEstado)
                    .addComponent(lblEstadoTitulo)
                    .addComponent(lblRolTitulo)
                    .addComponent(lblRolUsuario))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        menuAdmin.Opciones opciones = new menuAdmin.Opciones(lblUsuario.getText().replace("Usuario: ", ""), true,lblRolUsuario.getText().replace("Rol: ", ""));
        opciones.setVisible(true);

        // Cerrar el JFrame Opciones actual
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        int fila = tablaUsuarios.getSelectedRow();
        if(fila>=0){
            txtID.setText(tablaUsuarios.getValueAt(fila,0).toString());
            txtID.setEditable(false);
            txtNombre.setText(tablaUsuarios.getValueAt(fila, 1).toString());
            txtEdad.setText(tablaUsuarios.getValueAt(fila, 2).toString());
            txtPassword.setText(tablaUsuarios.getValueAt(fila, 4).toString());
            String rolActual = tablaUsuarios.getValueAt(fila, 3).toString();
            cbxRol.setSelectedItem(rolActual);
        }
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cargarUsuarios();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String ID = txtID.getText();
        String nombre = txtNombre.getText();
        String edad = txtEdad.getText();
        String rol = cbxRol.getSelectedItem().toString();
        String password = txtPassword.getText();

        if (ID.isEmpty() || nombre.isEmpty() || edad.isEmpty() || rol.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.","Error",1);
            return;
        }else{
            if(esNumero(edad)){
                if(Integer.parseInt(edad) >= 18){
                    String sql = "INSERT INTO usuario(id, nombre, edad, rol, contraseña) VALUES (?, ?,?, ?,?)";
                    try (Connection conn = Conexion.Conexion.getConexion();
                         PreparedStatement ps = conn.prepareStatement(sql)) {
                        ps.setString(1, ID);
                        ps.setString(2, nombre);
                        ps.setInt(3, Integer.parseInt(edad));
                        ps.setString(4, rol);
                        ps.setString(5, password);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Usuario agregado correctamente.");
                        cargarUsuarios();
                        limpiarCampos();
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, "Error al agregar: " + e.getMessage());
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "El valor ingresado en edad es invalido","Error",0);
                }
            }else{
                JOptionPane.showMessageDialog(this, "El valor ingresado en edad es invalido","Error",0);
            }
        }

        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int fila = tablaUsuarios.getSelectedRow();
	if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para editar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
	}

	String ID = txtID.getText();  // ID bloqueado, se usa para WHERE
	String nombre = txtNombre.getText();
	String edad = txtEdad.getText();
	String rol = cbxRol.getSelectedItem().toString();
	String password = txtPassword.getText();

        String sql = "UPDATE usuario SET nombre=?, edad=?, rol=?, contraseña=? WHERE id=?";
	try (Connection conn = Conexion.Conexion.getConexion();
	 PreparedStatement ps = conn.prepareStatement(sql)) {

	ps.setString(1, nombre);
	ps.setInt(2, Integer.parseInt(edad));
	ps.setString(3, rol);
	ps.setString(4, password);
	ps.setString(5, ID); // parámetro para WHERE

	ps.executeUpdate();

	JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
	cargarUsuarios(); // refrescar tabla
	limpiarCampos();  // limpiar formulario
	txtID.setEditable(true); // desbloquear ID para nuevo registro

	} catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tablaUsuarios.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idSeleccionado = tablaUsuarios.getValueAt(fila, 1).toString();
        String usuarioActivo = lblUsuario.getText().replace("Usuario: ", ""); // obtener usuario en sesión

        // Evitar eliminar al usuario en sesión
        if (idSeleccionado.equals(usuarioActivo)) {
            JOptionPane.showMessageDialog(this, "No puedes eliminar el usuario que está en sesión.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirmar eliminación
        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este usuario?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Ejecutar DELETE
        String id = (String) tablaUsuarios.getValueAt(fila, 0);
        String sql = "DELETE FROM usuario WHERE id=?";
        try (Connection conn = Conexion.Conexion.getConexion();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
            cargarUsuarios();
            limpiarCampos();
            txtID.setEditable(true); // desbloquear ID para nuevo registro
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtID.setEditable(true);
        limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed
    //ACTIVAR BOTÓN CANCELAR
    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtIDComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtIDComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDComponentAdded
    
    private static boolean esNumero(String entrada){
        try{
            Integer.parseInt(entrada);
            return true;
        }catch( NumberFormatException e){
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoTitulo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblRolTitulo;
    private javax.swing.JLabel lblRolUsuario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioTitulo;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
