/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menuAdmin;

import javax.swing.*;
import java.awt.*;
import login.LoginJFrame;
/**
 *
 * @author waldi
 */
public class Opciones extends javax.swing.JFrame {
    
    /**
     * Creates new form Opciones
     */
    public Opciones(String nombreUsuario, boolean conectado) {
        setTitle("Menú Administrador");
        setSize(400, 200);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // No cierra todo el programa
        initComponents();

        // Actualizar labels al iniciar
        setUsuario(nombreUsuario);
        setEstadoConexion(conectado);
    }

    
    public void setUsuario(String usuario) {
        lblUsuario.setText(usuario);
    }

    public void setEstadoConexion(boolean conectado) {
        if (conectado) {
            lblEstado.setText("Conectado");
            lblEstado.setForeground(Color.GREEN);
        } else {
            lblEstado.setText("Desconectado");
            lblEstado.setForeground(Color.RED);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnKardex = new javax.swing.JButton();
        lblEstadoTitulo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblUsuarioTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setText("¿Qué desea hacer?");

        btnUsuarios.setText("Ver Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnKardex.setText("Consultar Kardex");
        btnKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKardexActionPerformed(evt);
            }
        });

        lblEstadoTitulo.setText("Estado:");

        lblEstado.setText("none");

        lblUsuarioTitulo.setText("Usuario:");

        lblUsuario.setText("none");

        btnCerrar.setText("Cerrar Sesion");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnUsuarios))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnKardex)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblUsuarioTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEstadoTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnUsuarios)
                .addGap(32, 32, 32)
                .addComponent(btnKardex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoTitulo)
                    .addComponent(lblEstado)
                    .addComponent(lblUsuarioTitulo)
                    .addComponent(lblUsuario))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        //Cerrar sesion y abrir el menu login
        login.LoginJFrame login = new login.LoginJFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        menuAdmin.JFUsuarios usuarios = new menuAdmin.JFUsuarios(lblUsuario.getText().replace("Usuario: ", ""), true);
        usuarios.setVisible(true);

        // Cerrar el JFrame Opciones actual
        this.dispose();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKardexActionPerformed
        // TODO add your handling code here:
        menuAdmin.JFKardex kardex = new menuAdmin.JFKardex(lblUsuario.getText().replace("Usuario: ", ""), true);
        kardex.setVisible(true);

        // Cerrar el JFrame Opciones actual
        this.dispose();
    }//GEN-LAST:event_btnKardexActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnKardex;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioTitulo;
    // End of variables declaration//GEN-END:variables
}
