/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;
import Conexion.Conexion;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import menuAdmin.Opciones;
/**
 *
 * @author waldi
 */
public class LoginJFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginJFrame
     */
    public LoginJFrame() {
        setTitle("Iniciar Sesión");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setText("Usuario");

        lblPassword.setText("Contraseña");

        btnAceptar.setText("Iniciar Sesion");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassword)
                            .addComponent(lblUsuario))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnAceptar)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btnAceptar)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        String id = txtNombre.getText();
        String pass = String.valueOf(txtPassword.getPassword());

        if (id.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos","Advertencia",2);
            return;
        }

        dao.UsuarioDAO dao = new dao.UsuarioDAO();
        login.Usuario usuario = dao.login(id, pass);

        if (usuario != null) {
            JOptionPane.showMessageDialog(this, 
                "Bienvenido " + usuario.getNombre() + " (" + usuario.getRol() + ")");

            // Comparar rol
            if (usuario.getRol().equalsIgnoreCase("Administrador")) {
                // Abrir JFrame Opciones del paquete menuAdmin
                menuAdmin.Opciones opciones = new menuAdmin.Opciones(usuario.getNombre(), true, usuario.getRol()); // true = conectado
                opciones.setVisible(true);

                // Cerrar ventana de login
                this.dispose();
            }else{
                if (usuario.getRol().equalsIgnoreCase("Gestor de Inventario")) {
                    // Abrir JFrame Opciones del paquete menuAdmin
                    menuinventarioproducto.JFProducto producto = new menuinventarioproducto.JFProducto(usuario.getNombre(), true, usuario.getRol()); // true = conectado
                    producto.setVisible(true);

                    // Cerrar ventana de login
                    this.dispose();
                }else{
                    if (usuario.getRol().equalsIgnoreCase("Bodeguero")) {
                        // Abrir JFrame Opciones del paquete menuAdmin
                        menuinventarioproducto.JFProducto producto = new menuinventarioproducto.JFProducto(usuario.getNombre(), true, usuario.getRol()); // true = conectado
                        producto.setVisible(true);

                        // Cerrar ventana de login
                        this.dispose();
                    }else{
                        if (usuario.getRol().equalsIgnoreCase("Auditor")) {
                            // Abrir JFrame Opciones del paquete menuAdmin
                            menuAdmin.JFKardex kardex = new menuAdmin.JFKardex(usuario.getNombre(), true, usuario.getRol());
                            kardex.setVisible(true);

                            // Cerrar ventana de login
                            this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(this, 
                            "Su Usuario no tiene permisos\nComuniquese con el administrador para mejores soluciones.",
                            "Error al inicar sesión",0);
                        }
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, 
                "Usuario o contraseña incorrectos\nComuniquese con el administrador para mejores soluciones.",
                "Error al inicar sesión",0);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
