/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menuinventarioproducto;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import menuinventarioproducto.Producto;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author waldi
 */
public class JFProducto extends javax.swing.JFrame {

    /**
     * Creates new form JFProducto
     */
    public JFProducto(String nombreUsuario, boolean conectado, String rol) {
        setTitle("Inventario");
        initComponents();
        cargarProductos(); // Carga inicial al abrir la ventana
        cargarAlmacenes();//llenar el Combo Box de Almacen
        cargarCategorias();//llenar el Combo Box de Categoria
        cargarProveedores();//llenar el Combo Box de Proveedor
        
        setUsuario(nombreUsuario, rol);
        setEstadoConexion(conectado);
    }
    
    public void setUsuario(String usuario, String rol) {
        lblUsuario.setText(usuario);
        lblRol.setText(rol);
    }

    public void setEstadoConexion(boolean conectado) {
        if (conectado) {
            lblEstado.setText("Conectado");
            lblEstado.setForeground(Color.GREEN);
        } else {
            lblEstado.setText("Desconectado");
            lblEstado.setForeground(Color.RED);
        }
    }
    
    private void cargarProductos() {
        // Crear el modelo de la tabla con columnas
        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{
                "Código Lote", "Nombre", "Cantidad", "Almacén", 
                "Proveedor", "Categoría", "Vencimiento", "Descripción", "Costo"
            }, 0
        );

        try (Connection conn = Conexion.Conexion.getConexion();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM producto ORDER BY codigo_lote")) {

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("codigo_lote"),
                    rs.getString("nombre"),
                    rs.getInt("cantidad"),
                    rs.getString("almacen_codigo"),
                    rs.getString("proveedor_nit"),
                    rs.getString("categoria_codigo"),
                    rs.getDate("fechaDeVencimiento"),
                    rs.getString("descripcion"),
                    rs.getDouble("costo")
                });
            }

            tablaProducto.setModel(modelo);

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar productos: " + e.getMessage());
        }
    }
    
    private void cargarAlmacenes() {
        cmbAlmacen.removeAllItems(); // Limpia el combo antes de cargar
        for (Almacen a : Almacen.obtenerAlmacenes()) {
            cmbAlmacen.addItem(a); // Gracias al toString() se mostrará el nombre
        }
        
        cmbTraslado.removeAllItems(); // Limpia el combo antes de cargar
        for (Almacen a : Almacen.obtenerAlmacenes()) {
            cmbTraslado.addItem(a); // Gracias al toString() se mostrará el nombre
        }
    }
    
    private void cargarCategorias() {
        cmbCategoria.removeAllItems(); // Limpia el combo antes de cargar
        for (Categoria c : Categoria.obtenerCategorias()) {
            cmbCategoria.addItem(c); // Gracias al toString() se mostrará el nombre
        }
    }
    
    private void cargarProveedores() {
        cmbProveedor.removeAllItems(); // Limpiar combo
        for (Proveedor p : Proveedor.obtenerProveedores()) {
            cmbProveedor.addItem(p); // gracias al toString() se mostrará el nombre
        }
    }
    
    private void limpiarCampos() {
        String t = "";
        txtLote.setText(t);
        txtNombre.setText(t);
        txtCantidad.setText(t);
        txtCosto.setText(t);
        txtDescripcion.setText(t);
        fmfFechaVencimiento.setValue(2025-10-05);
        cmbAlmacen.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaProductos = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        btnIngreso = new javax.swing.JButton();
        lblIDLote = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblAlmacen = new javax.swing.JLabel();
        cmbAlmacen = new javax.swing.JComboBox<>();
        lblProveedor = new javax.swing.JLabel();
        cmbProveedor = new javax.swing.JComboBox<>();
        lblCategoria = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        lblFechaVencimiento = new javax.swing.JLabel();
        fmfFechaVencimiento = new javax.swing.JFormattedTextField();
        lblCosto = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblOpciones = new javax.swing.JLabel();
        lblRetiro = new javax.swing.JLabel();
        txtRetiro = new javax.swing.JTextField();
        btnSalida = new javax.swing.JButton();
        lblIngresar = new javax.swing.JLabel();
        txtIngresar = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnTraslado = new javax.swing.JButton();
        txtTraslado = new javax.swing.JLabel();
        cmbTraslado = new javax.swing.JComboBox<>();
        lblUsuarioTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblEstadoTitulo = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        lblRolTitulo = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductoMouseClicked(evt);
            }
        });
        tablaProductos.setViewportView(tablaProducto);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setText("Productos");

        btnIngreso.setText("Crear");
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });

        lblIDLote.setText("Codigo Lote");

        lblNombre.setText("Nombre");

        lblCantidad.setText("Cantidad");

        lblAlmacen.setText("Almacen");

        cmbAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlmacenActionPerformed(evt);
            }
        });

        lblProveedor.setText("Proveedor");

        lblCategoria.setText("Categoria");

        lblFechaVencimiento.setText("Fecha de Vencimiento");

        fmfFechaVencimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-M-dd"))));

        lblCosto.setText("Costo/U");

        lblDescripcion.setText("Descripcion");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblOpciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblOpciones.setText("Opciones");

        lblRetiro.setText("Retirar:");

        btnSalida.setText("Retirar");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        lblIngresar.setText("Ingresar");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnTraslado.setText("Traslado");
        btnTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrasladoActionPerformed(evt);
            }
        });

        txtTraslado.setText("Trasladar");

        cmbTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTrasladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lblOpciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRetiro)
                        .addGap(18, 18, 18)
                        .addComponent(txtRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTraslado)
                            .addComponent(btnSalida)
                            .addComponent(btnIngresar))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTraslado)
                            .addComponent(lblIngresar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOpciones)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRetiro)
                    .addComponent(txtRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalida))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngresar)
                    .addComponent(txtIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTraslado)
                    .addComponent(cmbTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTraslado)
                .addGap(71, 71, 71))
        );

        lblUsuarioTitulo.setText("Usuario:");

        lblUsuario.setText("none");

        lblEstado.setText("none");

        lblEstadoTitulo.setText("Estado:");

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        lblRolTitulo.setText("Rol:");

        lblRol.setText("none");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIDLote)
                                    .addComponent(lblProveedor)
                                    .addComponent(lblDescripcion))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblNombre)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblCantidad)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblAlmacen)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblCategoria)
                                                .addGap(18, 18, 18)
                                                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblFechaVencimiento)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fmfFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblCosto)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDescripcion)
                                        .addGap(20, 20, 20)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnIngreso)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnEditar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUsuarioTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblUsuario)))
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRolTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblRol)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblEstadoTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblEstado)
                                        .addGap(28, 28, 28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnActualizar)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCerrarSesion)))))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDLote)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlmacen)
                    .addComponent(cmbAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProveedor)
                    .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaVencimiento)
                    .addComponent(fmfFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCosto)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngreso)
                    .addComponent(btnActualizar)
                    .addComponent(btnCancelar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCerrarSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioTitulo)
                    .addComponent(lblUsuario)
                    .addComponent(lblEstado)
                    .addComponent(lblEstadoTitulo)
                    .addComponent(lblRolTitulo)
                    .addComponent(lblRol))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductoMouseClicked
        // TODO add your handling code here:
        int fila = tablaProducto.getSelectedRow();
        if(fila >= 0){
            // TextFields
            txtLote.setText(tablaProducto.getValueAt(fila, 0).toString());
            txtLote.setEnabled(false);
            cmbAlmacen.setEnabled(false);
            

            txtNombre.setText(tablaProducto.getValueAt(fila, 1).toString());
            txtCantidad.setText(tablaProducto.getValueAt(fila, 2).toString());
            txtDescripcion.setText(tablaProducto.getValueAt(fila, 7).toString());
            txtCosto.setText(tablaProducto.getValueAt(fila, 8).toString());

            // Fecha
            Object fechaObj = tablaProducto.getValueAt(fila, 6);
            if(fechaObj != null){
                fmfFechaVencimiento.setValue(fechaObj);
            } else {
                fmfFechaVencimiento.setValue(null);
            }

            // ComboBoxes (objetos) - comparar por código
            String almacenCodigo = tablaProducto.getValueAt(fila, 3).toString();
            for (int i = 0; i < cmbAlmacen.getItemCount(); i++) {
                menuinventarioproducto.Almacen a = (menuinventarioproducto.Almacen) cmbAlmacen.getItemAt(i);
                if(a.getCodigo().equals(almacenCodigo)){
                    cmbAlmacen.setSelectedIndex(i);
                    break;
                }
            }

            String proveedorNit = tablaProducto.getValueAt(fila, 4).toString();
            for (int i = 0; i < cmbProveedor.getItemCount(); i++) {
                menuinventarioproducto.Proveedor p = (menuinventarioproducto.Proveedor) cmbProveedor.getItemAt(i);
                if(p.getNit().equals(proveedorNit)){
                    cmbProveedor.setSelectedIndex(i);
                    break;
                }
            }

            String categoriaCodigo = tablaProducto.getValueAt(fila, 5).toString();
            for (int i = 0; i < cmbCategoria.getItemCount(); i++) {
                menuinventarioproducto.Categoria c = (menuinventarioproducto.Categoria) cmbCategoria.getItemAt(i);
                if(c.getCodigo().equals(categoriaCodigo)){
                    cmbCategoria.setSelectedIndex(i);
                    break;
                }
            }
        }
    }//GEN-LAST:event_tablaProductoMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cargarProductos(); // Carga inicial al abrir la ventana
        cargarAlmacenes();//llenar el Combo Box de Almacen
        cargarCategorias();//llenar el Combo Box de Categoria
        cargarProveedores();//llenar el Combo Box de Proveedor
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        txtLote.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        // TODO add your handling code here:
        String codigoLote = txtLote.getText().trim();
        String nombre = txtNombre.getText().trim();
        String cantidadStr = txtCantidad.getText().trim();
        String descripcion = txtDescripcion.getText().trim();
        String costoStr = txtCosto.getText().trim();
        java.util.Date fechaVencimiento = (java.util.Date) fmfFechaVencimiento.getValue();

        Almacen almacenSeleccionado = (Almacen) cmbAlmacen.getSelectedItem();
        Proveedor proveedorSeleccionado = (Proveedor) cmbProveedor.getSelectedItem();
        Categoria categoriaSeleccionada = (Categoria) cmbCategoria.getSelectedItem();

        // Validaciones básicas
        if (codigoLote.isEmpty() || nombre.isEmpty() || cantidadStr.isEmpty() || costoStr.isEmpty()
                || almacenSeleccionado == null || proveedorSeleccionado == null || categoriaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar números
        int cantidad;
        double costo;
        try {
            cantidad = Integer.parseInt(cantidadStr);
            if (cantidad < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cantidad inválida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            costo = Double.parseDouble(costoStr);
            if (costo < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Costo inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Insertar en la base de datos
        String sql = "INSERT INTO producto(codigo_lote, nombre, cantidad, almacen_codigo, proveedor_nit, categoria_codigo, fechaDeVencimiento, descripcion, costo) " +
                     "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try (Connection conn = Conexion.Conexion.getConexion();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, codigoLote);
            ps.setString(2, nombre);
            ps.setInt(3, cantidad);
            ps.setString(4, almacenSeleccionado.getCodigo());    // Llave primaria
            ps.setString(5, proveedorSeleccionado.getNit());     // Llave primaria
            ps.setString(6, categoriaSeleccionada.getCodigo());  // Llave primaria
            if (fechaVencimiento != null) {
                java.time.LocalDate localDate = fechaVencimiento.toInstant()
                        .atZone(java.time.ZoneId.systemDefault())
                        .toLocalDate();
                ps.setDate(7, java.sql.Date.valueOf(localDate));
            } else {
                ps.setNull(7, java.sql.Types.DATE);
            }
            ps.setString(8, descripcion);
            ps.setDouble(9, costo);

            ps.executeUpdate();
            
            //Crear movimiento crear producto
            String sqlMovimiento = "INSERT INTO movimiento_inventario (codigo, idtipo, codigo_lote, cantidad, costo, fecha) VALUES (?, ?, ?, ?, ?, ?)";

            try (PreparedStatement psMov = conn.prepareStatement(sqlMovimiento)) {
                // Generar código único de movimiento
                String codigoMovimiento = "MV" + (System.currentTimeMillis() % 1000000);

                // idtipo fijo para retiro (Crear)
                String idTipo = "TM05";

                // Obtener costo del producto actual
                double costoUnitario = Double.parseDouble(txtCosto.getText().trim());
                java.sql.Date fechaHoy = new java.sql.Date(System.currentTimeMillis());

                psMov.setString(1, codigoMovimiento);
                psMov.setString(2, idTipo);
                psMov.setString(3, codigoLote);
                psMov.setInt(4, cantidad);
                psMov.setDouble(5, costoUnitario);
                psMov.setDate(6, fechaHoy);

                psMov.executeUpdate();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al registrar el movimiento de inventario: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            JOptionPane.showMessageDialog(this, "Producto agregado correctamente.");

            // Recargar la tabla de productos y limpiar campos
            cargarProductos();
            txtLote.setEnabled(true);
            limpiarCampos();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al agregar producto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresoActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        // TODO add your handling code here:
        int fila = tablaProducto.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener valores
        String codigoLote = tablaProducto.getValueAt(fila, 0).toString();
        String cantidadStr = txtCantidad.getText().trim();
        String retiroStr = txtRetiro.getText().trim();

        // Validaciones
        int cantidadActual;
        int retiro;
        try {
            cantidadActual = Integer.parseInt(cantidadStr);
            retiro = Integer.parseInt(retiroStr);
            if (retiro <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad a retirar debe ser mayor que cero.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (retiro > cantidadActual) {
                JOptionPane.showMessageDialog(this, "No se puede retirar más de lo que hay en existencia.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Calcular nueva cantidad
        int nuevaCantidad = cantidadActual - retiro;

        // Actualizar base de datos
        String sql = "UPDATE producto SET cantidad = ? WHERE codigo_lote = ?";
        try (Connection conn = Conexion.Conexion.getConexion();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, nuevaCantidad);
            ps.setString(2, codigoLote);
            ps.executeUpdate();
            
            // Registrar movimiento de inventario (tipo "Venta" = Retiro)
            String sqlMovimiento = "INSERT INTO movimiento_inventario (codigo, idtipo, codigo_lote, cantidad, costo, fecha) VALUES (?, ?, ?, ?, ?, ?)";

            try (PreparedStatement psMov = conn.prepareStatement(sqlMovimiento)) {
                // Generar código único de movimiento
                String codigoMovimiento = "MV" + (System.currentTimeMillis() % 1000000);

                // idtipo fijo para retiro (Venta)
                String idTipo = "TM02";

                // Obtener costo del producto actual
                double costoUnitario = Double.parseDouble(txtCosto.getText().trim());
                java.sql.Date fechaHoy = new java.sql.Date(System.currentTimeMillis());

                psMov.setString(1, codigoMovimiento);
                psMov.setString(2, idTipo);
                psMov.setString(3, codigoLote);
                psMov.setInt(4, retiro);
                psMov.setDouble(5, costoUnitario);
                psMov.setDate(6, fechaHoy);

                psMov.executeUpdate();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al registrar el movimiento de inventario: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

            
            JOptionPane.showMessageDialog(this, "Retiro realizado correctamente.");

            // Recargar tabla y actualizar campo cantidad
            cargarProductos(); // Carga inicial al abrir la ventana
            cargarAlmacenes();//llenar el Combo Box de Almacen
            cargarCategorias();//llenar el Combo Box de Categoria
            cargarProveedores();//llenar el Combo Box de Proveedor
            txtLote.setEnabled(true);
            limpiarCampos();
            txtCantidad.setText(String.valueOf(nuevaCantidad));
            txtRetiro.setText(""); // Limpiar campo retiro

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al realizar retiro: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:                                          
        int fila = tablaProducto.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener valores
        String codigoLote = tablaProducto.getValueAt(fila, 0).toString();
        String cantidadStr = txtCantidad.getText().trim();
        String ingresoStr = txtIngresar.getText().trim();

        // Validaciones
        int cantidadActual;
        int ingreso;
        try {
            cantidadActual = Integer.parseInt(cantidadStr);
            ingreso = Integer.parseInt(ingresoStr);
            if (ingreso <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad a ingresar debe ser mayor que cero.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Calcular nueva cantidad
        int nuevaCantidad = cantidadActual + ingreso;

        // Actualizar base de datos
        String sql = "UPDATE producto SET cantidad = ? WHERE codigo_lote = ?";
        try (Connection conn = Conexion.Conexion.getConexion();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, nuevaCantidad);
            ps.setString(2, codigoLote);
            ps.executeUpdate();
            
            // Registrar movimiento de inventario (tipo "Compra" = Ingreso)
        String sqlMovimiento = "INSERT INTO movimiento_inventario (codigo, idtipo, codigo_lote, cantidad, costo, fecha) VALUES (?, ?, ?, ?, ?, ?)";

        try (PreparedStatement psMov = conn.prepareStatement(sqlMovimiento)) {
            // Generar código único de movimiento
            String codigoMovimiento = "MV" + (System.currentTimeMillis() % 1000000);

            // idtipo fijo para retiro (Venta)
            String idTipo = "TM01";

            // Obtener costo del producto actual
            double costoUnitario = Double.parseDouble(txtCosto.getText().trim());
            java.sql.Date fechaHoy = new java.sql.Date(System.currentTimeMillis());

            psMov.setString(1, codigoMovimiento);
            psMov.setString(2, idTipo);
            psMov.setString(3, codigoLote);
            psMov.setInt(4, ingreso);
            psMov.setDouble(5, costoUnitario);
            psMov.setDate(6, fechaHoy);

            psMov.executeUpdate();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al registrar el movimiento de inventario: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

            
            JOptionPane.showMessageDialog(this, "Ingreso realizado correctamente.");

            // Recargar tabla y actualizar campo cantidad
            cargarProductos(); // Carga inicial al abrir la ventana
            cargarAlmacenes();//llenar el Combo Box de Almacen
            cargarCategorias();//llenar el Combo Box de Categoria
            cargarProveedores();//llenar el Combo Box de Proveedor
            txtLote.setEnabled(true);
            limpiarCampos();
            txtCantidad.setText(String.valueOf(nuevaCantidad));
            txtIngresar.setText(""); // Limpiar campo ingreso

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al realizar ingreso: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tablaProducto.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String codigoLote = tablaProducto.getValueAt(fila, 0).toString();

        // Confirmar eliminación
        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este producto?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Ejecutar DELETE
        String sql = "DELETE FROM producto WHERE codigo_lote = ?";
        try (Connection conn = Conexion.Conexion.getConexion();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, codigoLote);
            ps.executeUpdate();
            
            //movmiento eliminar
            String sqlMovimiento = "INSERT INTO movimiento_inventario (codigo, idtipo, codigo_lote, cantidad, costo, fecha) VALUES (?, ?, ?, ?, ?, ?)";

            try (PreparedStatement psMov = conn.prepareStatement(sqlMovimiento)) {
                // Generar código único de movimiento
                String codigoMovimiento = "MV" + (System.currentTimeMillis() % 1000000);

                // idtipo fijo para retiro (eliminar)
                String idTipo = "TM07";

                // Obtener costo del producto actual
                int cantidad = Integer.parseInt(txtCantidad.getText().trim());
                double costoUnitario = Double.parseDouble(txtCosto.getText().trim());
                java.sql.Date fechaHoy = new java.sql.Date(System.currentTimeMillis());

                psMov.setString(1, codigoMovimiento);
                psMov.setString(2, idTipo);
                psMov.setString(3, codigoLote);
                psMov.setInt(4, cantidad);
                psMov.setDouble(5, costoUnitario);
                psMov.setDate(6, fechaHoy);

                psMov.executeUpdate();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al registrar el movimiento de inventario: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            JOptionPane.showMessageDialog(this, "Producto eliminado correctamente.");

            // Recargar tabla y limpiar campos
            cargarProductos(); // Carga inicial al abrir la ventana
            cargarAlmacenes();//llenar el Combo Box de Almacen
            cargarCategorias();//llenar el Combo Box de Categoria
            cargarProveedores();//llenar el Combo Box de Proveedor
            limpiarCampos();
            txtLote.setEnabled(true); // desbloquear txtLote para nuevo ingreso

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar producto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int fila = tablaProducto.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para editar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener datos del formulario
        String codigoLote = txtLote.getText().trim(); // ID bloqueado
        String nombre = txtNombre.getText().trim();
        String cantidadStr = txtCantidad.getText().trim();
        String costoStr = txtCosto.getText().trim();
        String descripcion = txtDescripcion.getText().trim();
        java.util.Date fechaVencimiento = (java.util.Date) fmfFechaVencimiento.getValue();

        Almacen almacenSeleccionado = (Almacen) cmbAlmacen.getSelectedItem();
        Proveedor proveedorSeleccionado = (Proveedor) cmbProveedor.getSelectedItem();
        Categoria categoriaSeleccionada = (Categoria) cmbCategoria.getSelectedItem();

        // Validaciones básicas
        if (nombre.isEmpty() || cantidadStr.isEmpty() || costoStr.isEmpty()
                || almacenSeleccionado == null || proveedorSeleccionado == null || categoriaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int cantidad;
        double costo;
        try {
            cantidad = Integer.parseInt(cantidadStr);
            if (cantidad < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cantidad inválida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            costo = Double.parseDouble(costoStr);
            if (costo < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Costo inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ejecutar UPDATE
        String sql = "UPDATE producto SET nombre=?, cantidad=?, almacen_codigo=?, proveedor_nit=?, categoria_codigo=?, fechaDeVencimiento=?, descripcion=?, costo=? " +
                     "WHERE codigo_lote=?";
        try (Connection conn = Conexion.Conexion.getConexion();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, nombre);
            ps.setInt(2, cantidad);
            ps.setString(3, almacenSeleccionado.getCodigo());
            ps.setString(4, proveedorSeleccionado.getNit());
            ps.setString(5, categoriaSeleccionada.getCodigo());

            java.sql.Date fechaSQL = null;
            if (fechaVencimiento != null) {
                fechaSQL = new java.sql.Date(fechaVencimiento.getTime());
            }
            ps.setDate(6, fechaSQL);

            ps.setString(7, descripcion);
            ps.setDouble(8, costo);
            ps.setString(9, codigoLote); // WHERE

            ps.executeUpdate();
            
            //Crear movimiento editar producto
            String sqlMovimiento = "INSERT INTO movimiento_inventario (codigo, idtipo, codigo_lote, cantidad, costo, fecha) VALUES (?, ?, ?, ?, ?, ?)";

            try (PreparedStatement psMov = conn.prepareStatement(sqlMovimiento)) {
                // Generar código único de movimiento
                String codigoMovimiento = "MV" + (System.currentTimeMillis() % 1000000);

                // idtipo fijo para retiro (editar)
                String idTipo = "TM06";

                // Obtener costo del producto actual
                double costoUnitario = Double.parseDouble(txtCosto.getText().trim());
                java.sql.Date fechaHoy = new java.sql.Date(System.currentTimeMillis());

                psMov.setString(1, codigoMovimiento);
                psMov.setString(2, idTipo);
                psMov.setString(3, codigoLote);
                psMov.setInt(4, cantidad);
                psMov.setDouble(5, costoUnitario);
                psMov.setDate(6, fechaHoy);

                psMov.executeUpdate();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al registrar el movimiento de inventario: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.");

            // Recargar tabla y limpiar campos
            cargarProductos(); // Carga inicial al abrir la ventana
            cargarAlmacenes();//llenar el Combo Box de Almacen
            cargarCategorias();//llenar el Combo Box de Categoria
            cargarProveedores();//llenar el Combo Box de Proveedor
            limpiarCampos();
            txtLote.setEnabled(true); // desbloquear txtLote para nuevo ingreso

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar producto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void cmbTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTrasladoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbTrasladoActionPerformed

    private void cmbAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAlmacenActionPerformed

    private void btnTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrasladoActionPerformed
        // TODO add your handling code here:                                           
        int fila = tablaProducto.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para trasladar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener datos del producto seleccionado
        String codigoLote = (String) tablaProducto.getValueAt(fila, 0); // Asumiendo que la primera columna tiene el codigo_lote
        Almacen almacenActual = (Almacen) cmbAlmacen.getSelectedItem(); // Ajusta según la columna del almacén en la tabla
        Almacen almacenDestino = (Almacen) cmbTraslado.getSelectedItem();

        if (almacenDestino == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un almacén de destino.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Verificar que no sea el mismo almacén
        if (almacenActual.getCodigo().equals(almacenDestino.getCodigo())) {
            JOptionPane.showMessageDialog(this, "No se pudo realizar el traslado: el producto ya está en ese almacén.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Ejecutar UPDATE solo para cambiar el almacén
        String sql = "UPDATE producto SET almacen_codigo=? WHERE codigo_lote=?";
        try (Connection conn = Conexion.Conexion.getConexion();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, almacenDestino.getCodigo());
            ps.setString(2, codigoLote);

            ps.executeUpdate();
            
            //movimiento traslado
            //Crear movimiento crear producto
            String sqlMovimiento = "INSERT INTO movimiento_inventario (codigo, idtipo, codigo_lote, cantidad, costo, fecha) VALUES (?, ?, ?, ?, ?, ?)";

            try (PreparedStatement psMov = conn.prepareStatement(sqlMovimiento)) {
                // Generar código único de movimiento
                String codigoMovimiento = "MV" + (System.currentTimeMillis() % 1000000);

                // idtipo fijo para retiro (Crear)
                String idTipo = "TM03";

                // Obtener costo del producto actual
                int cantidad = Integer.parseInt(txtCantidad.getText().trim());
                double costoUnitario = Double.parseDouble(txtCosto.getText().trim());
                java.sql.Date fechaHoy = new java.sql.Date(System.currentTimeMillis());

                psMov.setString(1, codigoMovimiento);
                psMov.setString(2, idTipo);
                psMov.setString(3, codigoLote);
                psMov.setInt(4, cantidad);
                psMov.setDouble(5, costoUnitario);
                psMov.setDate(6, fechaHoy);

                psMov.executeUpdate();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al registrar el movimiento de inventario: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            JOptionPane.showMessageDialog(this, "Traslado realizado correctamente.");

            cargarProductos(); // Carga inicial al abrir la ventana
            cargarAlmacenes();//llenar el Combo Box de Almacen
            cargarCategorias();//llenar el Combo Box de Categoria
            cargarProveedores();//llenar el Combo Box de Proveedor
            limpiarCampos();
            txtLote.setEnabled(true); // desbloquear txtLote para nuevo ingreso

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al trasladar el producto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTrasladoActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        login.LoginJFrame login = new login.LoginJFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed
//hola
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngreso;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnTraslado;
    private javax.swing.JComboBox<Almacen> cmbAlmacen;
    private javax.swing.JComboBox<Categoria> cmbCategoria;
    private javax.swing.JComboBox<Proveedor> cmbProveedor;
    private javax.swing.JComboBox<Almacen> cmbTraslado;
    private javax.swing.JFormattedTextField fmfFechaVencimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlmacen;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoTitulo;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JLabel lblIDLote;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblRetiro;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblRolTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioTitulo;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JScrollPane tablaProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIngresar;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRetiro;
    private javax.swing.JLabel txtTraslado;
    // End of variables declaration//GEN-END:variables
}
